server:
  port: 9000

spring:
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
#  web:
#    resources:
#      static-locations:
#        - file: "src/main/resources/"
#        - classpath: ["/templates/", "/static/", "/resources/"]
